### ISSUE TITLE
Client-side error after connecting twitter account

### ISSUE THREAD

**Issue by Synesso** [pseudozach/nostr.directory#8]
Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/)

After successfully authorising twitter account connection, the app loads 
`https://nostr.directory/twitter?accessToken=xxxx&accessSecret=xxxx&userId=3013745576&screenName=jemmawson`

The screen shows
`Application error: a client-side exception has occurred (see the browser console for more information).`

The console reads

```
Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"in_reply_to_status_id_str":null,"retweet_count":0,"user":{"favourites_count":96963,"statuses_count":105140,"location":null,"created_at":"Tue Aug 09 20:22:46 +0000 2011","followers_count":1769,"profile_text_color":"333333","contributors_enabled":false,"profile_use_background_image":true,"notifications":null,"listed_count":3,"default_profile_image":false,"follow_request_sent":null,"protected":false,"following":null,"lang":null,"profile_sidebar_fill_color":"DDEEF6","url":null,"profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png","id":351847987,"screen_name":"signal_and_rage","verified":false,"name":"Léon Musty","translator_type":"none","friends_count":63,"description":"suppressed until verified","profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","utc_offset":null,"withheld_in_countries":[],"default_profile":true,"profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png","is_translator":false,"geo_enabled":false,"profile_background_tile":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/351847987/1671164515","profile_image_url_https":"https://pbs.twimg.com/profile_images/1593995927114682368/Q6mOu9Ex_normal.jpg","time_zone":null,"profile_image_url":"http://pbs.twimg.com/profile_images/1593995927114682368/Q6mOu9Ex_normal.jpg","profile_background_color":"C0DEED","id_str":"351847987"},"createdAt":{"seconds":1671172566,"nanoseconds":205000000},"text":"Verifying my account on nostr\n\nMy Public Key: \"npub1fd2jplgmmjm0zx5ggl3vnq8s0w58xjy2p96xwxr016mgl92mjfesv25qk8\"\n\nFi… https://t.co/oYlNomJ20h","place":null,"in_reply_to_status_id":null,"id_str":"1603640067637104641","pubkey":"npub1fd2jplgmmjm0zx5ggl3vnq8s0w58xjy2p96xwxr016mgl92mjfesv25qk8","source":"<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>","favorite_count":0,"quote_count":0,"profileImageUrl":"https://pbs.twimg.com/profile_images/1593995927114682368/Q6mOu9Ex_normal.jpg","lang":"en","in_reply_to_user_id_str":null,"possibly_sensitive":false,"reply_count":0,"screenName":"signal_and_rage","userId":"351847987","in_reply_to_screen_name":null,"geo":null,"contributors":null,"extended_tweet":{"entities":{"urls":[{"expanded_url":"https://nostr.directory","display_url":"nostr.directory","url":"https://t.co/V5ONiAmA1I","indices":[128,151]}],"symbols":[],"user_mentions":[{"id":1603501251274379300,"indices":[152,167],"screen_name":"NostrDirectory","name":"nostr directory","id_str":"1603501251274379264"}],"hashtags":[]},"display_text_range":[0,167],"full_text":"Verifying my account on nostr\n\nMy Public Key: \"npub1fd2jplgmmjm0zx5ggl3vnq8s0w58xjy2p96xwxr016mgl92mjfesv25qk8\"\n\nFind others at https://t.co/V5ONiAmA1I @nostrdirectory"},"filter_level":"low","lcScreenName":"signal_and_rage","userName":"Léon Musty","in_reply_to_user_id":null,"timestamp_ms":"1671172560973","created_at":"Fri Dec 16 06:36:00 +0000 2022","entities":{"user_mentions":[],"symbols":[],"hashtags":[],"urls":[{"display_url":"twitter.com/i/web/status/1…","url":"https://t.co/oYlNomJ20h","expanded_url":"https://twitter.com/i/web/status/1603640067637104641","indices":[117,140]}]},"truncated":true,"is_quote_status":false,"coordinates":null,"isValid":false,"favorited":false,"retweeted":false,"nPubKey":"npub1fd2jplgmmjm0zx5ggl3vnq8s0w58xjy2p96xwxr016mgl92mjfesv25qk8","tweetId":"1603640067637104641","url":"https://t.co/oYlNomJ20h"}
    at 872-bad0e7888839d194.js:1:130878
    at ea (872-bad0e7888839d194.js:1:131089)
    at ta (872-bad0e7888839d194.js:1:131337)
    at 872-bad0e7888839d194.js:1:186638
    at Fi (framework-91d7f78b5b4003c8.js:1:104804)
    at t.unstable_runWithPriority (framework-91d7f78b5b4003c8.js:1:129511)
    at $l (framework-91d7f78b5b4003c8.js:1:44975)
    at Oi (framework-91d7f78b5b4003c8.js:1:104265)
    at vi (framework-91d7f78b5b4003c8.js:1:95722)
    at framework-91d7f78b5b4003c8.js:1:45198
```

**Comment by Synesso** [comment]
Same for Chrome Version 108.0.5359.124 (Official Build) (arm64)

**Comment by pseudozach** [comment]
can you please refresh and try again?
I pushed https://github.com/pseudozach/nostr.directory/commit/2288b972a541f01cbffb1ed361802ad421c27702 hoping it will help. I can't reproduce it on my side.

**Comment by Synesso** [comment]
Fixed! TY.

**Comment by Synesso** [comment]
My guess is that it was specific to my data, as I have a twitter follow who appears twice:

```
signal_and_rage
npub1504jj42t6flu5l6n7e389e9mt8gxduhnzuyv7dq4gr95w20mmpqscx0cg0
a3eb29554bd27fca7f53f66272e4bb59d066f2f31708cf341540cb4729fbd841
```

```
signal_and_rage
npub1fd2jplgmmjm0zx5ggl3vnq8s0w58xjy2p96xwxr016mgl92mjfesv25qk8
-
```

**Comment by pseudozach** [comment]
makes sense. thanks, good to hear it was resolved.
